version: '3'

services:
  transaction-lookup:
    build:
      context: ./tran_lookup
    ports:
      - "5001:5000"
    volumes:
      - ./tran_lookup:/app
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
    restart: always

  dispute-submission:
    build:
      context: ./tran_submission
    ports:
      - "5002:5000"
    volumes:
      - ./tran_submission:/app
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
    restart: always

networks:
  default:
    name: card-dispute-network