[project]
name = "fraud-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.0",
    "mcp-agent>=0.0.14",
]

[tool.uv.workspace]
members = ["tran_lookup", "tran_submission"]
